/// Domain model shared by the engine, persistence, and UI layers.
///
/// All physical quantities are SI (kg, cm, kcal, g) and named with a unit
/// suffix. Imperial conversion happens only at the UI edge (see [Units]).
library;

export 'src/biological_sex.dart';
export 'src/body_fat_method.dart';
export 'src/body_fat_observation.dart';
export 'src/body_mass_index.dart';
export 'src/calendar_date.dart';
export 'src/caution.dart';
export 'src/coaching_policy.dart';
export 'src/combine_latest.dart';
export 'src/daily_activity.dart';
export 'src/day_completeness.dart';
export 'src/food_energy.dart';
export 'src/food_entry.dart';
export 'src/goal_mode.dart';
export 'src/intake_day.dart';
export 'src/intake_day_from.dart';
export 'src/intake_days_from.dart';
export 'src/integration/backup_reader.dart';
export 'src/integration/backup_storage.dart';
export 'src/integration/backup_writer.dart';
export 'src/integration/clock.dart';
export 'src/integration/entitlement.dart';
export 'src/integration/entitlement_reader.dart';
export 'src/integration/entitlement_status.dart';
export 'src/integration/food_barcode_lookup.dart';
export 'src/integration/food_item.dart';
export 'src/integration/food_search.dart';
export 'src/integration/outcome.dart';
export 'src/integration/system_clock.dart';
export 'src/meal.dart';
export 'src/menstruation_day.dart';
export 'src/profile.dart';
export 'src/quantity_source.dart';
export 'src/repositories/data_eraser.dart';
export 'src/repositories/day_mark_reader.dart';
export 'src/repositories/day_mark_repository.dart';
export 'src/repositories/day_mark_writer.dart';
export 'src/repositories/food_day_reader.dart';
export 'src/repositories/food_entry_writer.dart';
export 'src/repositories/food_repository.dart';
export 'src/repositories/intake_reader.dart';
export 'src/repositories/preferences_reader.dart';
export 'src/repositories/preferences_repository.dart';
export 'src/repositories/preferences_writer.dart';
export 'src/repositories/recent_food_reader.dart';
export 'src/repositories/setup_reader.dart';
export 'src/repositories/setup_repository.dart';
export 'src/repositories/setup_writer.dart';
export 'src/repositories/waist_reader.dart';
export 'src/repositories/waist_repository.dart';
export 'src/repositories/waist_writer.dart';
export 'src/repositories/weight_reader.dart';
export 'src/repositories/weight_repository.dart';
export 'src/repositories/weight_writer.dart';
export 'src/screening_answers.dart';
export 'src/theme_preference.dart';
export 'src/training_status.dart';
export 'src/unit_system.dart';
export 'src/units.dart';
export 'src/user_setup.dart';
export 'src/waist_observation.dart';
export 'src/weight_observation.dart';
