import 'equipment.dart';
import 'exercise.dart';
import 'exercise_load.dart';
import 'health_connect_segment.dart';
import 'muscle_group.dart';

/// The exercises that ship with the app (MM-76). Not user-editable, so an
/// update can correct it; a user's own exercises are kept separately.
///
/// An exercise's [Exercise.id] is permanent: logged sets refer to it. Rename
/// an exercise by changing its name, never its id.
///
/// [Exercise.healthConnect] follows the table in MM-188 row by row. An
/// exercise that table does not list has none, which is the fallback
/// (MM-189), not an omission to fill in by resemblance.
const builtInExercises = <Exercise>[
  Exercise(
    id: 'barbell-bench-press',
    name: 'Barbell bench press',
    equipment: Equipment.barbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'dumbbell-bench-press',
    name: 'Dumbbell bench press',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'incline-barbell-bench-press',
    name: 'Incline barbell bench press',
    equipment: Equipment.barbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'incline-dumbbell-bench-press',
    name: 'Incline dumbbell bench press',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'decline-barbell-bench-press',
    name: 'Decline barbell bench press',
    equipment: Equipment.barbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'decline-dumbbell-bench-press',
    name: 'Decline dumbbell bench press',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'machine-chest-press',
    name: 'Machine chest press',
    equipment: Equipment.machine,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'smith-machine-bench-press',
    name: 'Smith machine bench press',
    equipment: Equipment.machine,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
  ),
  Exercise(
    id: 'push-up',
    name: 'Push-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'incline-push-up',
    name: 'Incline push-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'decline-push-up',
    name: 'Decline push-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'dip',
    name: 'Dip',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'dumbbell-fly',
    name: 'Dumbbell fly',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders],
  ),
  Exercise(
    id: 'incline-dumbbell-fly',
    name: 'Incline dumbbell fly',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders],
  ),
  Exercise(
    id: 'cable-crossover',
    name: 'Cable crossover',
    equipment: Equipment.cable,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders],
  ),
  Exercise(
    id: 'pec-deck',
    name: 'Pec deck',
    equipment: Equipment.machine,
    primary: MuscleGroup.chest,
    secondary: [MuscleGroup.shoulders],
  ),
  Exercise(
    id: 'pull-up',
    name: 'Pull-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.pullUp,
  ),
  Exercise(
    id: 'chin-up',
    name: 'Chin-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.pullUp,
  ),
  Exercise(
    id: 'neutral-grip-pull-up',
    name: 'Neutral-grip pull-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.pullUp,
  ),
  Exercise(
    id: 'weighted-pull-up',
    name: 'Weighted pull-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.pullUp,
  ),
  Exercise(
    id: 'assisted-pull-up',
    name: 'Assisted pull-up',
    equipment: Equipment.machine,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.pullUp,
  ),
  Exercise(
    id: 'muscle-up',
    name: 'Muscle-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.chest, MuscleGroup.triceps],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'lat-pulldown',
    name: 'Lat pulldown',
    equipment: Equipment.cable,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    healthConnect: HealthConnectSegment.latPullDown,
  ),
  Exercise(
    id: 'close-grip-lat-pulldown',
    name: 'Close-grip lat pulldown',
    equipment: Equipment.cable,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    healthConnect: HealthConnectSegment.latPullDown,
  ),
  Exercise(
    id: 'neutral-grip-lat-pulldown',
    name: 'Neutral-grip lat pulldown',
    equipment: Equipment.cable,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    healthConnect: HealthConnectSegment.latPullDown,
  ),
  Exercise(
    id: 'straight-arm-pulldown',
    name: 'Straight-arm pulldown',
    equipment: Equipment.cable,
    primary: MuscleGroup.back,
  ),
  Exercise(
    id: 'barbell-row',
    name: 'Barbell row',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
  ),
  Exercise(
    id: 'pendlay-row',
    name: 'Pendlay row',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
  ),
  Exercise(
    id: 'dumbbell-row',
    name: 'Dumbbell row',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    healthConnect: HealthConnectSegment.dumbbellRow,
  ),
  Exercise(
    id: 't-bar-row',
    name: 'T-bar row',
    equipment: Equipment.other,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
  ),
  Exercise(
    id: 'seated-cable-row',
    name: 'Seated cable row',
    equipment: Equipment.cable,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
  ),
  Exercise(
    id: 'machine-row',
    name: 'Machine row',
    equipment: Equipment.machine,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
  ),
  Exercise(
    id: 'chest-supported-row',
    name: 'Chest-supported row',
    equipment: Equipment.machine,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
  ),
  Exercise(
    id: 'inverted-row',
    name: 'Inverted row',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.biceps],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'dumbbell-pullover',
    name: 'Dumbbell pullover',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.chest],
  ),
  Exercise(
    id: 'machine-pullover',
    name: 'Machine pullover',
    equipment: Equipment.machine,
    primary: MuscleGroup.back,
  ),
  Exercise(
    id: 'back-extension',
    name: 'Back extension',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.backExtension,
  ),
  Exercise(
    id: 'rack-pull',
    name: 'Rack pull',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
  ),
  Exercise(
    id: 'barbell-shrug',
    name: 'Barbell shrug',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.forearms],
  ),
  Exercise(
    id: 'dumbbell-shrug',
    name: 'Dumbbell shrug',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.forearms],
  ),
  Exercise(
    id: 'deadlift',
    name: 'Deadlift',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.deadlift,
  ),
  Exercise(
    id: 'sumo-deadlift',
    name: 'Sumo deadlift',
    equipment: Equipment.barbell,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.back],
    healthConnect: HealthConnectSegment.deadlift,
  ),
  Exercise(
    id: 'trap-bar-deadlift',
    name: 'Trap-bar deadlift',
    equipment: Equipment.other,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.quads, MuscleGroup.hamstrings, MuscleGroup.back],
    healthConnect: HealthConnectSegment.deadlift,
  ),
  Exercise(
    id: 'romanian-deadlift',
    name: 'Romanian deadlift',
    equipment: Equipment.barbell,
    primary: MuscleGroup.hamstrings,
    secondary: [MuscleGroup.glutes, MuscleGroup.back],
    healthConnect: HealthConnectSegment.deadlift,
  ),
  Exercise(
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian deadlift',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.hamstrings,
    secondary: [MuscleGroup.glutes, MuscleGroup.back],
    healthConnect: HealthConnectSegment.deadlift,
  ),
  Exercise(
    id: 'stiff-leg-deadlift',
    name: 'Stiff-leg deadlift',
    equipment: Equipment.barbell,
    primary: MuscleGroup.hamstrings,
    secondary: [MuscleGroup.glutes, MuscleGroup.back],
    healthConnect: HealthConnectSegment.deadlift,
  ),
  Exercise(
    id: 'barbell-overhead-press',
    name: 'Barbell overhead press',
    equipment: Equipment.barbell,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.barbellShoulderPress,
  ),
  Exercise(
    id: 'seated-barbell-overhead-press',
    name: 'Seated barbell overhead press',
    equipment: Equipment.barbell,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.barbellShoulderPress,
  ),
  Exercise(
    id: 'push-press',
    name: 'Push press',
    equipment: Equipment.barbell,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps, MuscleGroup.quads],
    healthConnect: HealthConnectSegment.barbellShoulderPress,
  ),
  Exercise(
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell shoulder press',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.shoulderPress,
  ),
  Exercise(
    id: 'machine-shoulder-press',
    name: 'Machine shoulder press',
    equipment: Equipment.machine,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.shoulderPress,
  ),
  Exercise(
    id: 'arnold-press',
    name: 'Arnold press',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps],
    healthConnect: HealthConnectSegment.shoulderPress,
  ),
  Exercise(
    id: 'handstand-push-up',
    name: 'Handstand push-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'pike-push-up',
    name: 'Pike push-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.triceps],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell lateral raise',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.shoulders,
    healthConnect: HealthConnectSegment.dumbbellLateralRaise,
  ),
  Exercise(
    id: 'cable-lateral-raise',
    name: 'Cable lateral raise',
    equipment: Equipment.cable,
    primary: MuscleGroup.shoulders,
    healthConnect: HealthConnectSegment.lateralRaise,
  ),
  Exercise(
    id: 'machine-lateral-raise',
    name: 'Machine lateral raise',
    equipment: Equipment.machine,
    primary: MuscleGroup.shoulders,
    healthConnect: HealthConnectSegment.lateralRaise,
  ),
  Exercise(
    id: 'dumbbell-front-raise',
    name: 'Dumbbell front raise',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.shoulders,
    healthConnect: HealthConnectSegment.dumbbellFrontRaise,
  ),
  Exercise(
    id: 'cable-front-raise',
    name: 'Cable front raise',
    equipment: Equipment.cable,
    primary: MuscleGroup.shoulders,
    healthConnect: HealthConnectSegment.frontRaise,
  ),
  Exercise(
    id: 'plate-front-raise',
    name: 'Plate front raise',
    equipment: Equipment.other,
    primary: MuscleGroup.shoulders,
    healthConnect: HealthConnectSegment.frontRaise,
  ),
  Exercise(
    id: 'upright-row',
    name: 'Upright row',
    equipment: Equipment.barbell,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.back],
  ),
  Exercise(
    id: 'face-pull',
    name: 'Face pull',
    equipment: Equipment.cable,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.back],
  ),
  Exercise(
    id: 'dumbbell-reverse-fly',
    name: 'Dumbbell reverse fly',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.back],
  ),
  Exercise(
    id: 'cable-reverse-fly',
    name: 'Cable reverse fly',
    equipment: Equipment.cable,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.back],
  ),
  Exercise(
    id: 'reverse-pec-deck',
    name: 'Reverse pec deck',
    equipment: Equipment.machine,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.back],
  ),
  Exercise(
    id: 'battle-ropes',
    name: 'Battle ropes',
    equipment: Equipment.other,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.abs],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'turkish-get-up',
    name: 'Turkish get-up',
    equipment: Equipment.other,
    primary: MuscleGroup.shoulders,
    secondary: [MuscleGroup.abs, MuscleGroup.glutes],
  ),
  Exercise(
    id: 'barbell-curl',
    name: 'Barbell curl',
    equipment: Equipment.barbell,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'ez-bar-curl',
    name: 'EZ-bar curl',
    equipment: Equipment.barbell,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'dumbbell-curl',
    name: 'Dumbbell curl',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'incline-dumbbell-curl',
    name: 'Incline dumbbell curl',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'hammer-curl',
    name: 'Hammer curl',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'cable-hammer-curl',
    name: 'Cable hammer curl',
    equipment: Equipment.cable,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'preacher-curl',
    name: 'Preacher curl',
    equipment: Equipment.barbell,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'cable-curl',
    name: 'Cable curl',
    equipment: Equipment.cable,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'machine-curl',
    name: 'Machine curl',
    equipment: Equipment.machine,
    primary: MuscleGroup.biceps,
    secondary: [MuscleGroup.forearms],
    healthConnect: HealthConnectSegment.armCurl,
  ),
  Exercise(
    id: 'concentration-curl',
    name: 'Concentration curl',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.biceps,
  ),
  Exercise(
    id: 'reverse-curl',
    name: 'Reverse curl',
    equipment: Equipment.barbell,
    primary: MuscleGroup.forearms,
    secondary: [MuscleGroup.biceps],
  ),
  Exercise(
    id: 'wrist-curl',
    name: 'Wrist curl',
    equipment: Equipment.barbell,
    primary: MuscleGroup.forearms,
  ),
  Exercise(
    id: 'reverse-wrist-curl',
    name: 'Reverse wrist curl',
    equipment: Equipment.barbell,
    primary: MuscleGroup.forearms,
  ),
  Exercise(
    id: 'farmers-carry',
    name: "Farmer's carry",
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.forearms,
    secondary: [MuscleGroup.back, MuscleGroup.abs],
  ),
  Exercise(
    id: 'dead-hang',
    name: 'Dead hang',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.forearms,
    secondary: [MuscleGroup.back],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'close-grip-bench-press',
    name: 'Close-grip bench press',
    equipment: Equipment.barbell,
    primary: MuscleGroup.triceps,
    secondary: [MuscleGroup.chest, MuscleGroup.shoulders],
    healthConnect: HealthConnectSegment.benchPress,
  ),
  Exercise(
    id: 'triceps-pushdown',
    name: 'Triceps pushdown',
    equipment: Equipment.cable,
    primary: MuscleGroup.triceps,
  ),
  Exercise(
    id: 'rope-pushdown',
    name: 'Rope pushdown',
    equipment: Equipment.cable,
    primary: MuscleGroup.triceps,
  ),
  Exercise(
    id: 'skull-crusher',
    name: 'Skull crusher',
    equipment: Equipment.barbell,
    primary: MuscleGroup.triceps,
  ),
  Exercise(
    id: 'dumbbell-skull-crusher',
    name: 'Dumbbell skull crusher',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.triceps,
  ),
  Exercise(
    id: 'dumbbell-overhead-triceps-extension',
    name: 'Dumbbell overhead triceps extension',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.triceps,
    healthConnect: HealthConnectSegment.dumbbellTricepsExtensionTwoArm,
  ),
  Exercise(
    id: 'cable-overhead-triceps-extension',
    name: 'Cable overhead triceps extension',
    equipment: Equipment.cable,
    primary: MuscleGroup.triceps,
  ),
  Exercise(
    id: 'single-arm-dumbbell-triceps-extension',
    name: 'Single-arm dumbbell triceps extension',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.triceps,
    healthConnect: HealthConnectSegment.singleArmTricepsExtension,
  ),
  Exercise(
    id: 'single-arm-cable-triceps-extension',
    name: 'Single-arm cable triceps extension',
    equipment: Equipment.cable,
    primary: MuscleGroup.triceps,
    healthConnect: HealthConnectSegment.singleArmTricepsExtension,
  ),
  Exercise(
    id: 'machine-triceps-extension',
    name: 'Machine triceps extension',
    equipment: Equipment.machine,
    primary: MuscleGroup.triceps,
  ),
  Exercise(
    id: 'triceps-kickback',
    name: 'Triceps kickback',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.triceps,
  ),
  Exercise(
    id: 'bench-dip',
    name: 'Bench dip',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.triceps,
    secondary: [MuscleGroup.chest, MuscleGroup.shoulders],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'diamond-push-up',
    name: 'Diamond push-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.triceps,
    secondary: [MuscleGroup.chest, MuscleGroup.shoulders],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'crunch',
    name: 'Crunch',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.crunch,
  ),
  Exercise(
    id: 'cable-crunch',
    name: 'Cable crunch',
    equipment: Equipment.cable,
    primary: MuscleGroup.abs,
    healthConnect: HealthConnectSegment.crunch,
  ),
  Exercise(
    id: 'machine-crunch',
    name: 'Machine crunch',
    equipment: Equipment.machine,
    primary: MuscleGroup.abs,
    healthConnect: HealthConnectSegment.crunch,
  ),
  Exercise(
    id: 'bicycle-crunch',
    name: 'Bicycle crunch',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'reverse-crunch',
    name: 'Reverse crunch',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'sit-up',
    name: 'Sit-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.sitUp,
  ),
  Exercise(
    id: 'decline-sit-up',
    name: 'Decline sit-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.benchSitUp,
  ),
  Exercise(
    id: 'v-up',
    name: 'V-up',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'plank',
    name: 'Plank',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.plank,
  ),
  Exercise(
    id: 'side-plank',
    name: 'Side plank',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.plank,
  ),
  Exercise(
    id: 'hollow-hold',
    name: 'Hollow hold',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'dead-bug',
    name: 'Dead bug',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'lying-leg-raise',
    name: 'Lying leg raise',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.legRaise,
  ),
  Exercise(
    id: 'hanging-leg-raise',
    name: 'Hanging leg raise',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    secondary: [MuscleGroup.forearms],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.legRaise,
  ),
  Exercise(
    id: 'captains-chair-leg-raise',
    name: "Captain's chair leg raise",
    equipment: Equipment.other,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.legRaise,
  ),
  Exercise(
    id: 'hanging-knee-raise',
    name: 'Hanging knee raise',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    secondary: [MuscleGroup.forearms],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'toes-to-bar',
    name: 'Toes-to-bar',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    secondary: [MuscleGroup.forearms],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'ab-wheel-rollout',
    name: 'Ab wheel rollout',
    equipment: Equipment.other,
    primary: MuscleGroup.abs,
    secondary: [MuscleGroup.shoulders],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'russian-twist',
    name: 'Russian twist',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'cable-woodchopper',
    name: 'Cable woodchopper',
    equipment: Equipment.cable,
    primary: MuscleGroup.abs,
  ),
  Exercise(
    id: 'pallof-press',
    name: 'Pallof press',
    equipment: Equipment.cable,
    primary: MuscleGroup.abs,
  ),
  Exercise(
    id: 'mountain-climber',
    name: 'Mountain climber',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.abs,
    secondary: [MuscleGroup.shoulders, MuscleGroup.quads],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.mountainClimber,
  ),
  Exercise(
    id: 'medicine-ball-slam',
    name: 'Medicine-ball slam',
    equipment: Equipment.other,
    primary: MuscleGroup.abs,
    secondary: [MuscleGroup.shoulders, MuscleGroup.back],
    healthConnect: HealthConnectSegment.ballSlam,
  ),
  Exercise(
    id: 'barbell-hip-thrust',
    name: 'Barbell hip thrust',
    equipment: Equipment.barbell,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.hipThrust,
  ),
  Exercise(
    id: 'machine-hip-thrust',
    name: 'Machine hip thrust',
    equipment: Equipment.machine,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.hipThrust,
  ),
  Exercise(
    id: 'glute-bridge',
    name: 'Glute bridge',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'cable-kickback',
    name: 'Cable kickback',
    equipment: Equipment.cable,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings],
  ),
  Exercise(
    id: 'hip-abduction',
    name: 'Hip abduction',
    equipment: Equipment.machine,
    primary: MuscleGroup.glutes,
  ),
  Exercise(
    id: 'cable-pull-through',
    name: 'Cable pull-through',
    equipment: Equipment.cable,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings],
  ),
  Exercise(
    id: 'reverse-hyperextension',
    name: 'Reverse hyperextension',
    equipment: Equipment.machine,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings, MuscleGroup.back],
  ),
  Exercise(
    id: 'kettlebell-swing',
    name: 'Kettlebell swing',
    equipment: Equipment.other,
    primary: MuscleGroup.glutes,
    secondary: [MuscleGroup.hamstrings, MuscleGroup.back],
    healthConnect: HealthConnectSegment.kettlebellSwing,
  ),
  Exercise(
    id: 'back-squat',
    name: 'Back squat',
    equipment: Equipment.barbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.squat,
  ),
  Exercise(
    id: 'front-squat',
    name: 'Front squat',
    equipment: Equipment.barbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
    healthConnect: HealthConnectSegment.squat,
  ),
  Exercise(
    id: 'goblet-squat',
    name: 'Goblet squat',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
    healthConnect: HealthConnectSegment.squat,
  ),
  Exercise(
    id: 'box-squat',
    name: 'Box squat',
    equipment: Equipment.barbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.squat,
  ),
  Exercise(
    id: 'bodyweight-squat',
    name: 'Bodyweight squat',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.squat,
  ),
  Exercise(
    id: 'smith-machine-squat',
    name: 'Smith machine squat',
    equipment: Equipment.machine,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.squat,
  ),
  Exercise(
    id: 'hack-squat',
    name: 'Hack squat',
    equipment: Equipment.machine,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
  ),
  Exercise(
    id: 'leg-press',
    name: 'Leg press',
    equipment: Equipment.machine,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.legPress,
  ),
  Exercise(
    id: 'single-leg-leg-press',
    name: 'Single-leg leg press',
    equipment: Equipment.machine,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.legPress,
  ),
  Exercise(
    id: 'leg-extension',
    name: 'Leg extension',
    equipment: Equipment.machine,
    primary: MuscleGroup.quads,
    healthConnect: HealthConnectSegment.legExtension,
  ),
  Exercise(
    id: 'forward-lunge',
    name: 'Forward lunge',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.lunge,
  ),
  Exercise(
    id: 'reverse-lunge',
    name: 'Reverse lunge',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.lunge,
  ),
  Exercise(
    id: 'walking-lunge',
    name: 'Walking lunge',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.lunge,
  ),
  Exercise(
    id: 'lateral-lunge',
    name: 'Lateral lunge',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
  ),
  Exercise(
    id: 'split-squat',
    name: 'Split squat',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
  ),
  Exercise(
    id: 'bulgarian-split-squat',
    name: 'Bulgarian split squat',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
  ),
  Exercise(
    id: 'step-up',
    name: 'Step-up',
    equipment: Equipment.dumbbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes],
  ),
  Exercise(
    id: 'wall-sit',
    name: 'Wall sit',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.quads,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'box-jump',
    name: 'Box jump',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.calves],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'sled-push',
    name: 'Sled push',
    equipment: Equipment.other,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.glutes, MuscleGroup.calves],
  ),
  Exercise(
    id: 'thruster',
    name: 'Thruster',
    equipment: Equipment.barbell,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.shoulders, MuscleGroup.glutes],
  ),
  Exercise(
    id: 'burpee',
    name: 'Burpee',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.quads,
    secondary: [MuscleGroup.chest, MuscleGroup.shoulders],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.burpee,
  ),
  Exercise(
    id: 'lying-leg-curl',
    name: 'Lying leg curl',
    equipment: Equipment.machine,
    primary: MuscleGroup.hamstrings,
    healthConnect: HealthConnectSegment.legCurl,
  ),
  Exercise(
    id: 'seated-leg-curl',
    name: 'Seated leg curl',
    equipment: Equipment.machine,
    primary: MuscleGroup.hamstrings,
    healthConnect: HealthConnectSegment.legCurl,
  ),
  Exercise(
    id: 'standing-leg-curl',
    name: 'Standing leg curl',
    equipment: Equipment.machine,
    primary: MuscleGroup.hamstrings,
    healthConnect: HealthConnectSegment.legCurl,
  ),
  Exercise(
    id: 'good-morning',
    name: 'Good morning',
    equipment: Equipment.barbell,
    primary: MuscleGroup.hamstrings,
    secondary: [MuscleGroup.glutes, MuscleGroup.back],
  ),
  Exercise(
    id: 'nordic-curl',
    name: 'Nordic curl',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.hamstrings,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'glute-ham-raise',
    name: 'Glute-ham raise',
    equipment: Equipment.other,
    primary: MuscleGroup.hamstrings,
    secondary: [MuscleGroup.glutes],
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'standing-calf-raise',
    name: 'Standing calf raise',
    equipment: Equipment.machine,
    primary: MuscleGroup.calves,
  ),
  Exercise(
    id: 'seated-calf-raise',
    name: 'Seated calf raise',
    equipment: Equipment.machine,
    primary: MuscleGroup.calves,
  ),
  Exercise(
    id: 'leg-press-calf-raise',
    name: 'Leg press calf raise',
    equipment: Equipment.machine,
    primary: MuscleGroup.calves,
  ),
  Exercise(
    id: 'single-leg-calf-raise',
    name: 'Single-leg calf raise',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.calves,
    load: ExerciseLoad.bodyweight,
  ),
  Exercise(
    id: 'jump-rope',
    name: 'Jump rope',
    equipment: Equipment.other,
    primary: MuscleGroup.calves,
    secondary: [MuscleGroup.shoulders],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.jumpRope,
  ),
  Exercise(
    id: 'jumping-jack',
    name: 'Jumping jack',
    equipment: Equipment.bodyweight,
    primary: MuscleGroup.calves,
    secondary: [MuscleGroup.shoulders],
    load: ExerciseLoad.bodyweight,
    healthConnect: HealthConnectSegment.jumpingJack,
  ),
  Exercise(
    id: 'power-clean',
    name: 'Power clean',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.glutes, MuscleGroup.quads, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.weightlifting,
  ),
  Exercise(
    id: 'hang-clean',
    name: 'Hang clean',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.glutes, MuscleGroup.quads, MuscleGroup.hamstrings],
    healthConnect: HealthConnectSegment.weightlifting,
  ),
  Exercise(
    id: 'clean-and-jerk',
    name: 'Clean and jerk',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.glutes, MuscleGroup.quads, MuscleGroup.shoulders],
    healthConnect: HealthConnectSegment.weightlifting,
  ),
  Exercise(
    id: 'snatch',
    name: 'Snatch',
    equipment: Equipment.barbell,
    primary: MuscleGroup.back,
    secondary: [MuscleGroup.glutes, MuscleGroup.quads, MuscleGroup.shoulders],
    healthConnect: HealthConnectSegment.weightlifting,
  ),
];
